# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {2}  -id {filemgmt 20-1318}  -string {{WARNING: [filemgmt 20-1318] Duplicate Design Unit 'SUM(bhd)' found in library 'xil_defaultlib'
Duplicate found at line 14 of file C:/Users/Diego/Desktop/Arqui/Proyecto/Proyecto/Extras/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/operadores.vhd
	(Active) Duplicate found at line 16 of file C:/Users/Diego/Desktop/Arqui/Proyecto/Proyecto/Extras/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/resta.vhd}}  -suppress 
set_msg_config  -ruleid {3}  -id {Common 17-349}  -string {{INFO: [Common 17-349] Got license for feature 'Synthesis' and/or device 'xc7a35t-cpg236'}}  -suppress 
set_msg_config  -ruleid {4}  -id {HDL 9-849}  -string {{CRITICAL WARNING: [HDL 9-849] Syntax error : file ended before end of clause. [C:/Users/Diego/Desktop/Arqui/Proyecto/Proyecto/Extras/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/operadores.vhd:93]}}  -suppress 
set_msg_config  -ruleid {5}  -id {Synth 8-2715}  -string {{ERROR: [Synth 8-2715] syntax error near : [C:/Users/Diego/Desktop/Arqui/Proyecto/Proyecto/Extras/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Clock_Divider.vhd:18]}}  -suppress 
set_msg_config  -ruleid {6}  -id {Synth 8-1031}  -string {{ERROR: [Synth 8-1031] slow_max is not declared [C:/Users/Diego/Desktop/Arqui/Proyecto/Proyecto/Extras/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Clock_Divider.vhd:30]}}  -suppress 
set_msg_config  -ruleid {7}  -id {Synth 8-2810}  -string {{INFO: [Synth 8-2810] unit behavioral ignored due to previous errors [C:/Users/Diego/Desktop/Arqui/Proyecto/Proyecto/Extras/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Clock_Divider.vhd:13]}}  -suppress 
set_msg_config  -ruleid {8}  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
set_msg_config  -ruleid {9}  -id {Common 17-206}  -string {{INFO: [Common 17-206] Exiting Vivado at Sat Sep  2 01:27:29 2017...}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/ALU.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/C_U.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Clock_Divider.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Debouncer.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Display_Controller.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/FA.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Mux.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/PC.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/RAM.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/ROM.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Reg.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Status.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/operadores.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/resta.vhd}
  {C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/imports/new/Basys3.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Diego/Desktop/RepoArqui/2017-2-G06/proyecto/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}]


synth_design -top Basys3 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Basys3.dcp

catch { report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb }
